# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segreteria_dialog_inoltra_prenotazione.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InoltraPrenotazione(object):
    def setupUi(self, InoltraPrenotazione):
        InoltraPrenotazione.setObjectName("InoltraPrenotazione")
        InoltraPrenotazione.resize(745, 263)
        self.gridLayout = QtWidgets.QGridLayout(InoltraPrenotazione)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("text-align:center")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(InoltraPrenotazione)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(InoltraPrenotazione)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 6, 1, 1)

        self.retranslateUi(InoltraPrenotazione)
        QtCore.QMetaObject.connectSlotsByName(InoltraPrenotazione)

    def retranslateUi(self, InoltraPrenotazione):
        _translate = QtCore.QCoreApplication.translate
        InoltraPrenotazione.setWindowTitle(_translate("InoltraPrenotazione", "StudiSync - Segreteria Incoltra Prenotazione"))
        self.label.setText(_translate("InoltraPrenotazione", "Matricola"))
        self.label_7.setText(_translate("InoltraPrenotazione", "Azione"))
        self.label_4.setText(_translate("InoltraPrenotazione", "Studenti In Attesa"))
        self.label_6.setText(_translate("InoltraPrenotazione", "Data Richiesta"))
        self.label_3.setText(_translate("InoltraPrenotazione", "Cognome"))
        self.label_2.setText(_translate("InoltraPrenotazione", "Nome"))
        self.label_5.setText(_translate("InoltraPrenotazione", "Esame Richiesto"))
