# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'students_home_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Students_Home(object):
    def setupUi(self, Students_Home):
        Students_Home.setObjectName("Students_Home")
        Students_Home.resize(1178, 644)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        Students_Home.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Students_Home)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.username_title_label = QtWidgets.QLabel(self.centralwidget)
        self.username_title_label.setGeometry(QtCore.QRect(60, 20, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.username_title_label.setFont(font)
        self.username_title_label.setObjectName("username_title_label")
        self.matricola_title_label = QtWidgets.QLabel(self.centralwidget)
        self.matricola_title_label.setGeometry(QtCore.QRect(960, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.matricola_title_label.setFont(font)
        self.matricola_title_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.matricola_title_label.setObjectName("matricola_title_label")
        self.date_title_label = QtWidgets.QLabel(self.centralwidget)
        self.date_title_label.setGeometry(QtCore.QRect(440, 20, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.date_title_label.setFont(font)
        self.date_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_title_label.setObjectName("date_title_label")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(570, 570, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.image.setFont(font)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("logo_studisync.jpeg"))
        self.image.setScaledContents(True)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        Students_Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Students_Home)
        QtCore.QMetaObject.connectSlotsByName(Students_Home)

    def retranslateUi(self, Students_Home):
        _translate = QtCore.QCoreApplication.translate
        Students_Home.setWindowTitle(_translate("Students_Home", "StudiSync"))
        self.title_label.setText(_translate("Students_Home", "Ciao"))
        self.username_title_label.setText(_translate("Students_Home", "NOME, COGNOME"))
        self.matricola_title_label.setText(_translate("Students_Home", "0124001234"))
        self.date_title_label.setText(_translate("Students_Home", "Lunedì, 01/01/1970 09:00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Students_Home = QtWidgets.QMainWindow()
    ui = Ui_Students_Home()
    ui.setupUi(Students_Home)
    Students_Home.show()
    sys.exit(app.exec_())
